<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.cheers.arch</groupId>
        <artifactId>cheers-framework</artifactId>
        <version>1.0.0-snapshot</version>
    </parent>
    <artifactId>cheers-category</artifactId>
    <packaging>jar</packaging>
    <name>cheers-category</name>
    <description>分类管理模块</description>

    <dependencies>
        <!-- 依赖 cheers-common 基础模块 -->
        <dependency>
            <groupId>com.cheers.arch</groupId>
            <artifactId>cheers-common</artifactId>
        </dependency>

        <!-- 依赖 cheers-mybatis 模块 -->
        <dependency>
            <groupId>com.cheers.arch</groupId>
            <artifactId>cheers-mybatis</artifactId>
        </dependency>

        <!-- 依赖 cheers-web 模块 -->
        <dependency>
            <groupId>com.cheers.arch</groupId>
            <artifactId>cheers-web</artifactId>
        </dependency>

        <!-- 依赖 cheers-redis 模块 -->
        <dependency>
            <groupId>com.cheers.arch</groupId>
            <artifactId>cheers-redis</artifactId>
        </dependency>

        <!-- 依赖 cheers-test 模块 -->
        <dependency>
            <groupId>com.cheers.arch</groupId>
            <artifactId>cheers-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project> 