<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.cheers.arch</groupId>
        <artifactId>tunnel-management</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.cheers.arch</groupId>
    <artifactId>cheers-module-dynamic-business</artifactId>
    <packaging>jar</packaging>

    <name>${project.artifactId}</name>
    <description>动态业务模块</description>

    <dependencies>
        <!-- 业务组件 -->
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-common</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-mybatis</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-web</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-security</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-redis</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-tree</artifactId>
            <version>${revision}</version>
        </dependency>

        <!-- 工具类相关 -->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct-processor</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>

        <!-- Test 测试相关 -->
        <dependency>
            <groupId>com.cheers</groupId>
            <artifactId>cheers-framework-test</artifactId>
            <version>${revision}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project> 